// Ponto único de import dos ícones outline (Tabler) usados no Bank —
// evita espalhar `@tabler/icons-react` pelo app.
export {
  IconPlus,
  IconArrowsExchange,
  IconUpload,
  IconCreditCard,
  IconChartLine,
  IconChartPie,
  IconPigMoney,
  IconTarget,
  IconArrowUpRight,
  IconArrowDownRight,
  IconHome,
  IconReceipt,
  IconCoins,
  IconWallet,
  IconShoppingCart,
  IconToolsKitchen2,
  IconPackage,
  IconPill,
  IconGasStation,
  IconBeach,
  IconDeviceTv,
  IconDots,
  IconCash,
  IconRepeat,
  IconTrendingUp,
  IconTrendingDown,
  IconCalendarEvent,
  IconCheck,
  IconChevronDown,
  IconChevronRight,
  IconChevronLeft,
  IconRefresh,
  IconUser,
  IconEye,
  IconEyeOff,
  IconSchool,
  IconHeartbeat,
  IconCar,
  IconTrash,
  IconX,
  IconPencil,
} from "@tabler/icons-react";
